src/Entity/Manga.php
<?php

namespace App\Entity;

use App\Repository\MangaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MangaRepository::class)]
class Manga extends Book
{
    #[ORM\ManyToOne(inversedBy: 'mangas')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Serie $serie = null;

    #[ORM\Column]
    private ?int $volume_number = null;

    #[ORM\OneToOne(mappedBy: 'manga', cascade: ['persist', 'remove'])]
    private ?Stock $stock = null;

    #[ORM\OneToMany(mappedBy: 'manga', targetEntity: Borrowing::class, orphanRemoval: true)]
    private Collection $borrowings;

    #[ORM\OneToMany(mappedBy: 'manga', targetEntity: Purchase::class, orphanRemoval: true)]
    private Collection $purchases;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Image $image = null;

    public function __construct()
    {
        $this->borrowings = new ArrayCollection();
        $this->purchases = new ArrayCollection();
    }

    public function getSerie(): ?Serie
    {
        return $this->serie;
    }

    public function setSerie(?Serie $serie): self
    {
        $this->serie = $serie;

        return $this;
    }

    public function getVolumeNumber(): ?int
    {
        return $this->volume_number;
    }

    public function setVolumeNumber(int $volume_number): self
    {
        $this->volume_number = $volume_number;

        return $this;
    }

    public function getStock(): ?Stock
    {
        return $this->stock;
    }

    public function setStock(Stock $stock): self
    {
        // set the owning side of the relation if necessary
        if ($stock->getManga() !== $this) {
            $stock->setManga($this);
        }

        $this->stock = $stock;

        return $this;
    }

    /**
     * @return ArrayCollection<int, Borrowing>
     */
    public function getBorrowings(): ArrayCollection
    {
        return $this->borrowings;
    }

    public function addBorrowing(Borrowing $borrowing): self
    {
        if (!$this->borrowings->contains($borrowing)) {
            $this->borrowings->add($borrowing);
            $borrowing->setManga($this);
        }

        return $this;
    }

    public function removeBorrowing(Borrowing $borrowing): self
    {
        if ($this->borrowings->removeElement($borrowing)) {
            // set the owning side to null (unless already changed)
            if ($borrowing->getManga() === $this) {
                $borrowing->setManga(null);
            }
        }

        return $this;
    }

    /**
     * @return ArrayCollection<int, Purchase>
     */
    public function getPurchases(): ArrayCollection
    {
        return $this->purchases;
    }

    public function addPurchase(Purchase $purchase): self
    {
        if (!$this->purchases->contains($purchase)) {
            $this->purchases->add($purchase);
            $purchase->setManga($this);
        }

        return $this;
    }

    public function removePurchase(Purchase $purchase): self
    {
        if ($this->purchases->removeElement($purchase)) {
            // set the owning side to null (unless already changed)
            if ($purchase->getManga() === $this) {
                $purchase->setManga(null);
            }
        }

        return $this;
    }

    public function getImage(): ?Image
    {
        return $this->image;
    }

    public function setImage(?Image $image): self
    {
        $this->image = $image;

        return $this;
    }
}

src/Form/MangaType.php
<?php

namespace App\Form;

use App\Entity\Manga;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class MangaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('volume_number', IntegerType:: class, [
            'attr' => [
                'class' => 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'
            ],
            'label_attr' => [
                'class' => "mt-2 block text-gray-700 text-sm font-bold mb-2"
            ]
        ])
            ->add('title', TextType:: class, [
            'required' => false,
            'attr' => [
                'class' => 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'
            ],
            'label_attr' => [
                'class' => "mt-2 block text-gray-700 text-sm font-bold mb-2"
            ],
        ])
            ->add('summary', TextareaType:: class, [
            'attr' => [
                'class' => 'shadow appearance-none border rounded w-full h-60 py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'
            ],
            'label_attr' => [
                'class' => "mt-2 block text-gray-700 text-sm font-bold mb-2"
            ]
        ])
            ->add('price', NumberType:: class, [
            'attr' => [
                'class' => 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'
            ],
            'label_attr' => [
                'class' => "mt-2 block text-gray-700 text-sm font-bold mb-2"
            ]
        ])
            ->add('edited_at', DateType:: class, [
            'widget' => 'single_text',
            'attr' => [
                'class' => 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'
            ],
            'label_attr' => [
                'class' => "mt-2 block text-gray-700 text-sm font-bold mb-2"
            ]
        ])
            ->add('stock', StockType:: class, [
            'attr' => [
                'class' => 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'
            ],
            'label_attr' => [
                'class' => "mt-2 block text-gray-700 text-sm font-bold mb-2"
            ]
        ])
            ->add('image', ImageType:: class, [
            'attr' => [
                'class' => 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'
            ],
            'label_attr' => [
                'class' => "mt-2 block text-gray-700 text-sm font-bold mb-2"
            ]
        ])
            ->add('Enregistrer', SubmitType::class, [
                'attr' => [
                    'class' => 'bg-amber-500 hover:bg-amber-700 text-white font-bold mt-2 py-2 px-4 rounded focus:outline-none focus:shadow-outline'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Manga::class,
        ]);
    }
}

src/Controller/MangaController.php
<?php

namespace App\Controller;

use App\Entity\Borrowing;
use DateTimeZone;
use App\Entity\Manga;
use App\Entity\Serie;
use App\Form\BorrowingType;
use App\Form\MangaType;
use App\Repository\BorrowingRepository;
use App\Repository\MangaRepository;
use App\Services\isGranted;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;

class MangaController extends AbstractController
{
    private $entityManager;
    private $repo;
    private $borrowingRepo;

    public function __construct(EntityManagerInterface $em, MangaRepository $repo, BorrowingRepository $borrowingRepo)
    {
        $this->entityManager = $em;
        $this->repo = $repo;
        $this->borrowingRepo = $borrowingRepo;
    }
    
    #[Route('/admin/mangas', name: 'app_admin_manga')]
    public function adminList(): Response
    {
        $mangas = $this->repo->findAllOrderBy('created_at', 'ASC');


        return $this->render('admin/manga/list.html.twig', [
            'mangas' => $mangas,
        ]);
    }
    
    #[Route('/admin/serie/{serie}/mangas', name: 'app_admin_serie_manga')]
    public function adminIndex(Serie $serie): Response
    {
        $mangas = $this->repo->findBySerie($serie);


        return $this->render('admin/manga/index.html.twig', [
            'mangas' => $mangas,
            'serie' => $serie
        ]);
    }


    #[Route('/admin/serie/{serie}/manga/create', name: 'app_admin_serie_manga_create')]
    public function create(Request $request, Serie $serie): Response
    {
        $manga = new Manga();

        $form = $this->createForm(MangaType::class, $manga);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {

            $file = $form->get('image')['file']->getData();
            $extension = $file->guessExtension();
            if (!$extension) {
                // extension cannot be guessed
                $extension = 'bin';
            }

            $imageName = str_replace(' ', '-', strtolower("{$serie->getName()}-tome-{$request->get('manga')['volume_number']}"));

            $file->move(
                $this->getParameter('images_directory'),
                $imageName . "." . $extension
            );

            $manga->getImage()->setName($imageName);
            $manga->getImage()->setUrl("/assets/images/" . strtolower($imageName) . "." . $extension);
            
            $manga->setCreatedAt(new \DateTimeImmutable('now', new DateTimeZone('Europe/Paris')));
            $manga->setSerie($serie);
            
            $this->entityManager->persist($manga);
            $this->entityManager->flush();
            
            return $this->redirectToRoute('app_admin_serie_manga', ['serie' => $serie->getId()]);
        }

        return $this->render('admin/manga/create.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/admin/serie/{serie}/manga/update/{manga}', name: 'app_admin_serie_manga_update')]
    public function update(Request $request, Serie $serie, Manga $manga): Response
    {
        $manga = $this->repo->find($manga);

        $form = $this->createForm(MangaType::class, $manga);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {

            $file = $form->get('image')['file']->getData();
            if($file){

                $extension = $file->guessExtension();
                if (!$extension) {
                    // extension cannot be guessed
                    $extension = 'bin';
                }
                
                $imageName = str_replace(' ', '-', strtolower("{$serie->getName()}-tome-{$request->get('manga')['volume_number']}"));
                
                $file->move(
                    $this->getParameter('images_directory'),
                    $imageName . "." . $extension
                );
                
                $manga->getImage()->setName($imageName);
                $manga->getImage()->setUrl("/assets/images/" . strtolower($imageName) . "." . $extension);
            }
            
            $manga->setSerie($serie);
            
            $this->entityManager->persist($manga);
            $this->entityManager->flush();
            
            return $this->redirectToRoute('app_admin_serie_manga', ['serie' => $serie->getId()]);
        }

        return $this->render('admin/manga/update.html.twig', [
            'form' => $form->createView(),
            'manga' => $manga
        ]);
    }

    #[Route('/manga/{manga}', name: 'app_manga')]
    public function show(Manga $manga, Request $request): Response
    {
        $borrowing = new Borrowing();
        $form = $this->createForm(BorrowingType::class, $borrowing);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {

            $verificator = new IsGranted();
            $isGranted = $verificator->verifySubscription($this->getUser(), $manga, $this->borrowingRepo);

            if ($isGranted) {

                $borrowing->setBorrowingDate(new \DateTimeImmutable('now'), new DateTimeZone('Europe/Paris'));
                $borrowing->setIsReturned(false);
                $borrowing->setUser($this->getUser());
                $borrowing->setManga($manga);

                $manga->getStock()->setQuantity(($manga->getStock()->getQuantity()) - 1);

                $this->entityManager->persist($borrowing);
                $this->entityManager->persist($manga);
                $this->entityManager->flush();

                $this->addFlash('success', 'Votre emprunt à bien été enregistrer');

                return $this->redirectToRoute('app_manga', ['manga' => $manga->getId()]);
            } else {
                $this->addFlash('error', 'Vous ne pouvez pas emprunter de manga');

                return $this->redirectToRoute('app_manga', ['manga' => $manga->getId()]);
            }
        }

        return $this->render('client/manga/show.html.twig', [
            'manga' => $manga,
            'form' => $form->createView()
        ]);
    }
}

templates/client/manga/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}MangaTech | {{ manga.serie.name }} Tome {{ manga.volumeNumber }}
{% endblock %}

{% block body %}
{% for message in app.flashes('success') %}
	<div class="rounded-md bg-green-50 p-4">
		<div class="flex">
			<div class="flex-shrink-0">
				<svg class="h-5 w-5 text-green-400" viewbox="0 0 20 20" fill="currentColor" aria-hidden="true">
					<path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd"/>
				</svg>
			</div>
			<div class="ml-3">
				<p class="text-sm font-medium text-green-800">{{ message }}</p>
			</div>
			<div class="ml-auto pl-3">
				<div class="-mx-1.5 -my-1.5">
					<button type="button" class="inline-flex rounded-md bg-green-50 p-1.5 text-green-500 hover:bg-green-100 focus:outline-none focus:ring-2 focus:ring-green-600 focus:ring-offset-2 focus:ring-offset-green-50">
						<span class="sr-only">Dismiss</span>
						<svg class="h-5 w-5" viewbox="0 0 20 20" fill="currentColor" aria-hidden="true">
							<path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z"/>
						</svg>
					</button>
				</div>
			</div>
		</div>
	</div>
{% endfor %}
{% for message in app.flashes('error') %}
	<div class="rounded-md bg-red-50 p-4">
		<div class="flex">
			<div class="flex-shrink-0">
				<svg class="h-5 w-5 text-red-400" viewbox="0 0 20 20" fill="currentColor" aria-hidden="true">
					<path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd"/>
				</svg>
			</div>
			<div class="ml-3">
				<p class="text-sm font-medium text-red-800">{{ message }}</p>
			</div>
			<div class="ml-auto pl-3">
				<div class="-mx-1.5 -my-1.5">
					<button type="button" class="inline-flex rounded-md bg-red-50 p-1.5 text-red-500 hover:bg-red-100 focus:outline-none focus:ring-2 focus:ring-red-600 focus:ring-offset-2 focus:ring-offset-red-50">
						<span class="sr-only">Dismiss</span>
						<svg class="h-5 w-5" viewbox="0 0 20 20" fill="currentColor" aria-hidden="true">
							<path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z"/>
						</svg>
					</button>
				</div>
			</div>
		</div>
	</div>
{% endfor %}

	
<div class="bg-white">
	<div
		class="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl flex lg:gap-x-8 lg:px-8">
		<!-- Product details -->
		<div class="w-3/6">
			<nav aria-label="Breadcrumb">
				<ol role="list" class="flex items-center space-x-2">
					<li>
						<div class="flex items-center text-sm">
							<a href="/serie/{{ manga.serie.id }}" class="font-medium text-gray-500 hover:text-gray-900">{{ manga.serie.name }}</a>
							<svg viewbox="0 0 20 20" fill="currentColor" aria-hidden="true" class="ml-2 h-5 w-5 flex-shrink-0 text-gray-300">
								<path d="M5.555 17.776l8-16 .894.448-8 16-.894-.448z"/>
							</svg>
						</div>
					</li>
					<li>
						<div class="flex items-center text-sm">
							<p href="" class="font-medium text-gray-500 hover:text-gray-900">Tome {{ manga.volumeNumber }}</p>
						</div>
					</li>
				</ol>
			</nav>

			<div class="mt-4">
				<h1 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">{{ manga.serie.name }} Tome {{ manga.volumeNumber }}</h1>
                <h2 class="text-2xl font-bold tracking-tight text-gray-900 sm:text-4xl">{{ manga.title ? manga.title : "" }}</h2>
			</div>

			<section aria-labelledby="information-heading" class="mt-4">
				<h2 id="information-heading" class="sr-only">Product information</h2>

				<div class="flex items-center">
					<p class="text-lg text-gray-900 sm:text-xl">{{ manga.price|number_format(2) }} €</p>
				</div>

				<div class="mt-4 space-y-6">
					<p class="text-base text-gray-500">{{ manga.summary }}</p>
				</div>

				<div class="mt-6 flex items-center">
					<svg class="h-5 w-5 flex-shrink-0 text-green-500" viewbox="0 0 20 20" fill="currentColor" aria-hidden="true">
						<path fill-rule="evenodd" d="M16.704 4.153a.75.75 0 01.143 1.052l-8 10.5a.75.75 0 01-1.127.075l-4.5-4.5a.75.75 0 011.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 011.05-.143z" clip-rule="evenodd"/>
					</svg>
					<p class="ml-2 text-sm text-gray-500">{{ manga.stock.quantity }} {{ manga.stock.quantity|length != 0 ? "exemplaires restant" : "exemplaire restant" }}</p>
				</div>
                
                <!-- Product form -->
                <div class="mt-10 lg:col-start-1 lg:row-start-2 lg:max-w-lg lg:self-start">
                    <section aria-labelledby="options-heading">
                        <h2 id="options-heading" class="sr-only">Product options</h2>

                        {{ form(form) }}
                    </section>
                </div>
			</section>
		</div>

		<!-- Product image -->
		<div class="mt-10 lg:mt-0 lg:self-center mx-auto">
			<div class="aspect-h-1 aspect-w-1 overflow-hidden rounded-lg">
				<img src="{{ asset(manga.getImage().url) }}" alt="Model wearing light green backpack with black canvas straps and front zipper pouch." class="h-full w-full object-cover object-center">
			</div>
		</div>

	</div>
</div>


{% endblock %}