src/Entity/Subscription.php
<?php

namespace App\Entity;

use App\Repository\SubscriptionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SubscriptionRepository::class)]
class Subscription
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?float $monthly_price = null;

    #[ORM\OneToMany(mappedBy: 'subscription', targetEntity: User::class)]
    private Collection $users;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getMonthlyPrice(): ?float
    {
        return $this->monthly_price;
    }

    public function setMonthlyPrice(float $monthly_price): self
    {
        $this->monthly_price = $monthly_price;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->setSubscription($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getSubscription() === $this) {
                $user->setSubscription(null);
            }
        }

        return $this;
    }
}

src/Form/SubscriptionType.php
<?php

namespace App\Form;

use App\Entity\Subscription;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SubscriptionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('type', TextType:: class, [
            'attr' => [
                'class' => 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'
            ],
            'label_attr' => [
                'class' => "mt-2 block text-gray-700 text-sm font-bold mb-2"
            ]
        ])
            ->add('description', TextareaType:: class, [
            'attr' => [
                'class' => 'shadow appearance-none border rounded w-full h-60 py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'
            ],
            'label_attr' => [
                'class' => "mt-2 block text-gray-700 text-sm font-bold mb-2"
            ]
        ])
            ->add('monthly_price', MoneyType:: class, [
            'attr' => [
                'class' => 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'
            ],
            'label_attr' => [
                'class' => "mt-2 block text-gray-700 text-sm font-bold mb-2"
            ]
        ])
            ->add('Enregistrer', SubmitType::class, [
            'attr' => [
                'class' => 'bg-amber-500 hover:bg-amber-700 text-white font-bold mt-2 py-2 px-4 rounded focus:outline-none focus:shadow-outline'
            ]
        ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Subscription::class,
        ]);
    }
}

src/Controller/SubscriptionController.php
<?php

namespace App\Controller;

use App\Entity\Subscription;
use App\Form\SubscriptionType;
use App\Repository\SubscriptionRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SubscriptionController extends AbstractController
{
    private $entityManager;
    private $repo;
    private $userRepo;

    public function __construct(EntityManagerInterface $em, SubscriptionRepository $repo, UserRepository $userRepo)
    {
        $this->entityManager = $em;
        $this->repo = $repo;
        $this->userRepo = $userRepo;
    }
    
    #[Route('/admin/subscriptions', name: 'app_admin_subscriptions')]
    public function adminIndex(): Response
    {
        $subs = $this->repo->findAll();

        return $this->render('admin/subscription/index.html.twig', [
            'subs' => $subs,
        ]);
    }


    #[Route('/admin/subscription/create', name: 'app_admin_subscription_create')]
    public function create(Request $request): Response
    {
        $sub = new Subscription();

        $form = $this->createForm(SubscriptionType::class, $sub);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {


            $this->entityManager->persist($sub);
            $this->entityManager->flush();


            return $this->redirectToRoute('app_admin_subscriptions');
        }

        return $this->render('admin/subscription/create.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/admin/subscription/update/{sub}', name: 'app_admin_subscription_update')]
    public function update(Request $request, Subscription $sub): Response
    {
        $sub = $this->repo->find($sub);

        $form = $this->createForm(SubscriptionType::class, $sub);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {


            $this->entityManager->persist($sub);
            $this->entityManager->flush();


            return $this->redirectToRoute('app_admin_subscriptions');
        }

        return $this->render('admin/subscription/update.html.twig', [
            'form' => $form->createView(),
            'sub' => $sub
        ]);
    }


    #[Route('/subscriptions', name: 'app_subscriptions')]
    public function index(): Response
    {
        $subs = $this->repo->findAll();

        return $this->render('client/subscription/index.html.twig', [
            'subs' => $subs,
        ]);
    }


    #[Route('/user/subscription', name: 'app_user_subscription')]
    public function subscribe(Request $request): Response
    {
        $user_id = $request->request->get('user_id');
        $sub_id = $request->request->get('sub_id');
        
        $user = $this->userRepo->find($user_id);
        $sub = $this->repo->find($sub_id);

        $user->setSubscription($sub);

        $this->entityManager->persist($user);
        $this->entityManager->flush();

        $this->addFlash('subscribSuccess', 'Vous êtes maintenant abonné');

        return $this->redirectToRoute('app_home');
    }
}

templates/client/subscription/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}MangaTech | Abonnements
{% endblock %}

{% block body %}


<div class="bg-white py-24 sm:py-32">
	<div class="mx-auto max-w-7xl px-6 lg:px-8">
		<div class="mx-auto max-w-4xl text-center">
			<h2 class="text-base font-semibold leading-7 text-amber-600">Abonnements</h2>
			<p class="mt-2 text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl">A chacun son abonnement</p>
		</div>
		<p class="mx-auto mt-6 max-w-2xl text-center text-lg leading-8 text-gray-600">Quel type de lecteur êtes vous ? Choisissez en fonction du type de contenu que vous voulez et du nombres de manga que vous voudriez emprunter à la fois.</p>
		<div class="isolate mx-auto mt-10 grid max-w-md grid-cols-1 gap-8 lg:mx-0 lg:max-w-none lg:grid-cols-3">
        {% for sub in subs %}
        {% set modalities = sub.description|split('- ') %}
            <div x-data="{open : false}" class="rounded-3xl p-8 xl:p-10 ring-2 ring-amber-600">

				<div class="flex items-center justify-between gap-x-4">
					<h3 id="tier-startup" class="text-lg font-semibold leading-8 text-amber-600">{{ sub.type }}</h3>
				</div>
				<p
					class="mt-6 flex items-baseline gap-x-1">
					<!-- Price, update based on frequency toggle state -->
					<span class="text-4xl font-bold tracking-tight text-gray-900">{{ sub.monthlyPrice }} €</span>
					<!-- Payment frequency, update based on frequency toggle state -->
					<span class="text-sm font-semibold leading-6 text-gray-600">/mois</span>
				</p>
				<a  @click="open = !open" aria-describedby="tier-startup" class="mt-6 block rounded-md py-2 px-3 text-center text-sm font-semibold leading-6 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-amber-600 bg-amber-600 text-white shadow-sm hover:bg-amber-500">S'abonner</a>

                <div x-show="open"  
                    class="relative z-10" aria-labelledby="modal-title" role="dialog" aria-modal="true">
                    
                    <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"></div>

                    <div class="fixed inset-0 z-10 overflow-y-auto">
                        <div
                            class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
                            
                            <div class="relative transform overflow-hidden rounded-lg bg-white px-4 pb-4 pt-5 text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg sm:p-6">
                                <div>
                                    <div class="mt-3 text-center sm:mt-5">
                                        <h3 class="text-base font-semibold leading-6 text-gray-900" id="modal-title">Valider le cet abonnement</h3>
                                    </div>
                                </div>
                                <div class="mt-5 sm:mt-6 sm:grid sm:grid-flow-row-dense sm:grid-cols-1 sm:gap-3">
                                    <form action="{{ path('app_user_subscription') }}" method="POST">
                                        <input type="hidden" name="user_id" value="{{ app.user.id }}">
                                        <input type="hidden" name="sub_id" value="{{ sub.id }}">
                                        <button type="submit" class="inline-flex w-full justify-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 sm:col-start-2">Je suis certain</button>
                                    </form>
                                    <button @click="open = false" type="button" class="mt-3 inline-flex w-full justify-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 sm:col-start-1 sm:mt-0">Annuler</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

				<ul role="list" class="mt-8 space-y-3 text-sm leading-6 text-gray-600 xl:mt-10">
                {% for modality in modalities %}
                    {% if modality != "" %}
                        <li class="flex gap-x-3">
                            <svg class="h-6 w-5 flex-none text-amber-600" viewbox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                <path fill-rule="evenodd" d="M16.704 4.153a.75.75 0 01.143 1.052l-8 10.5a.75.75 0 01-1.127.075l-4.5-4.5a.75.75 0 011.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 011.05-.143z" clip-rule="evenodd"/>
                            </svg>
                            {{ modality }}
                        </li>
                    {%  endif %}
                {% endfor %}
				</ul>
			</div>
            {% endfor %}
		</div>
	</div>
</div>




{% endblock %}